### ISSUE TITLE
Hi,i encountered a problem now!

### ISSUE THREAD

**Issue by ThomasSunKai** [nazarhussain/camalian#2]
when i use this,why this line comes:DEPRECATION: The cocaine gem is deprecated. Please upgrade to terrapin. See https://github.com/thoughtbot/terrapin/ for further instructions.

**Comment by nazarhussain** [comment]
I will check and get back to you in couple of days. But I encourage if you want to open up PR to fix this issue.

**Comment by nazarhussain** [comment]
@ThomasSunKai Probably its tool late now. I updated and published a newer version. Which have native Ruby implementation and no dependency of Rmagic. Please try and let me know if it works.
